Added Kubernetes commands.
moabukar/Everything-Tech pull request #40
Opened 2021-11-28 10:18 UTC by alihasanahmedkhan

1. Added the useful Kubernetes commands.
2. Formated the docker commands.

2021-11-28 12:53 UTC, moabukar requested changes
please address the code reviews, thanks

2021-11-28 12:53 UTC, moabukar commented on Containers-&-Orchestration/Docker/docker_commands.md
>  docker run -d alihasanahmedkhan/helloworld:lastest
you mean "latest" instead of "lastest"?

2021-11-28 12:53 UTC, moabukar commented on Containers-&-Orchestration/Kubernetes-K8s/kubernetes_commands.md
> +# Required tools for running K8's:
"...for running *Local* K8s"

2021-11-28 16:02 UTC, alihasanahmedkhan commented on Containers-&-Orchestration/Docker/docker_commands.md
>  docker run -d alihasanahmedkhan/helloworld:lastest
Yes its typo

2021-11-28 16:02 UTC, alihasanahmedkhan commented on Containers-&-Orchestration/Kubernetes-K8s/kubernetes_commands.md
> +# Required tools for running K8's:
Yes exactly.

2021-11-29 10:38 UTC, moabukar commented on Containers-&-Orchestration/Docker/docker_commands.md
>  docker run -d alihasanahmedkhan/helloworld:lastest
ok please fix and commit again

2021-11-29 10:40 UTC, moabukar requested changes
fix docker image names "lastest" to "latest"

2021-11-29 11:31 UTC, moabukar commented
lgtm

2021-11-29 11:31 UTC, moabukar approved these changes
lgtm

2021-11-29 11:32 UTC, merged

2021-11-29 12:03 UTC, alihasanahmedkhan commented
Thanks, Muhammad Abukar.